name: docsgpt-oss
services:
  frontend:
    image: 'scott292/docsgpt-oss-frontend-1:latest'
    volumes:
      - '../frontend/src:/app/src'
    environment:
      - 'VITE_API_HOST=http://backend:7091'
      - 'VITE_API_STREAMING=true'
    ports:
      - '8453:5173'
    depends_on:
      - backend

  backend:
    image: 'scott292/docsgpt-oss-backend-1:latest'
    environment:
      - 'API_KEY=not-needed'
      - 'EMBEDDINGS_KEY=$API_KEY'
      - 'LLM_PROVIDER=openai'
      - 'LLM_NAME=gemma3:12b''
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
      - 'CELERY_RESULT_BACKEND=redis://redis:6379/1'
      - 'MONGO_URI=mongodb://mongo:27017/docsgpt'
      - 'CACHE_REDIS_URL=redis://redis:6379/2'
      - 'OPENAI_BASE_URL=http://ollama-api-j4ks4808sscgw00gggk8w884:11434/v1'
    volumes:
      - '../application/indexes:/app/indexes'
      - '../application/inputs:/app/inputs'
      - '../application/vectors:/app/vectors'
    depends_on:
      - redis
      - mongo

 worker:
    image: 'scott292/docsgpt-oss-worker-1'
    command: 'celery -A application.app.celery worker -l INFO -B'
    environment:
      - 'API_KEY=not-needed'
      - 'EMBEDDINGS_KEY=$API_KEY'
      - 'LLM_PROVIDER=openai'
      - 'LLM_NAME=gemma3:12b'
      - 'CELERY_BROKER_URL=redis://redis:6379/0'
      - 'CELERY_RESULT_BACKEND=redis://redis:6379/1'
      - 'MONGO_URI=mongodb://mongo:27017/docsgpt'
      - 'API_URL=http://backend:7091'
      - 'CACHE_REDIS_URL=redis://redis:6379/2'
    volumes:
      - '../application/indexes:/app/indexes'
      - '../application/inputs:/app/inputs'
      - '../application/vectors:/app/vectors'
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6-alpine

  mongo:
    image: mongo:6
    volumes:
      - 'mongodb_data_container:/data/db'

volumes:
  mongodb_data_container:
